"""Fix Decimal Value on Column

Revision ID: 3294aab122c1
Revises: 
Create Date: 2025-04-05 22:28:08.478245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3294aab122c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databarang',
    sa.Column('kode_barang', sa.String(), nullable=False),
    sa.Column('nama_barang', sa.String(), nullable=False),
    sa.Column('satuan', sa.String(), nullable=False),
    sa.Column('kelompok', sa.String(), nullable=False),
    sa.Column('kadaluarsa', sa.String(), nullable=False),
    sa.Column('harga_pokok', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('stok_minimal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('kode_barang')
    )
    op.create_table('kelompok',
    sa.Column('kelompok', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('kelompok')
    )
    op.create_table('pelanggan',
    sa.Column('kode_pelanggan', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('telp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('kode_pelanggan')
    )
    op.create_table('satuan',
    sa.Column('satuan', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('satuan')
    )
    op.create_table('supplier',
    sa.Column('kode_supplier', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('telp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('kode_supplier')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password', sa.LargeBinary(length=60), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.Column('current_logged_in', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pembelianhd',
    sa.Column('no_faktur', sa.String(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('kode_supplier', sa.String(), nullable=False),
    sa.Column('kode_pengguna', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['kode_pengguna'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kode_supplier'], ['supplier.kode_supplier'], ),
    sa.PrimaryKeyConstraint('no_faktur')
    )
    op.create_table('penjualanhd',
    sa.Column('no_faktur', sa.String(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('kode_pengguna', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=2), nullable=False),
    sa.Column('ppn', sa.Numeric(precision=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=2), nullable=False),
    sa.Column('bayar', sa.Numeric(precision=2), nullable=False),
    sa.Column('kembali', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['kode_pengguna'], ['users.id'], ),
    sa.PrimaryKeyConstraint('no_faktur')
    )
    op.create_table('pembeliandt',
    sa.Column('no_faktur', sa.String(), nullable=False),
    sa.Column('kode_barang', sa.String(), nullable=False),
    sa.Column('nama_barang', sa.String(), nullable=False),
    sa.Column('harga_beli', sa.Numeric(precision=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['no_faktur'], ['pembelianhd.no_faktur'], ),
    sa.PrimaryKeyConstraint('no_faktur')
    )
    op.create_table('penjualandt',
    sa.Column('no_faktur', sa.String(), nullable=False),
    sa.Column('kode_barang', sa.String(), nullable=False),
    sa.Column('nama_barang', sa.String(), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['no_faktur'], ['penjualanhd.no_faktur'], ),
    sa.PrimaryKeyConstraint('no_faktur')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penjualandt')
    op.drop_table('pembeliandt')
    op.drop_table('penjualanhd')
    op.drop_table('pembelianhd')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('supplier')
    op.drop_table('satuan')
    op.drop_table('pelanggan')
    op.drop_table('kelompok')
    op.drop_table('databarang')
    # ### end Alembic commands ###
